<?php error_reporting (E_ERROR);error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
$sid_db="dbcp05";
$usr_db="tlccourier_user";
$pwd_db="TLCCourrier001!";
$db_db = "tlccourier_bd";
$conection = mysql_connect($sid_db, $usr_db, $pwd_db);mysql_select_db($db_db, $conection) or die('ERROR DE CONECCION LINEA 12');
echo mysql_errno($conection) . ": " . mysql_error($conection). "\n";
mysql_query ("SET NAMES 'utf8'");$connection = mysqli_connect($sid_db, $usr_db, $pwd_db, $db_db);
mysqli_query($connection ,"SET NAMES 'utf8'");$datehoy = date('d-m-Y');$dir_archivos="../archivos/" ;$path_archivo="../archivos/";$urllocal = "../webpanel/login.php";$urllocal_wp = "../";

// Valida a los usuarios ingresados en la administracion,
// Chequea los permisos para entrar a las diferentes secciones.
if(!function_exists('valida_usuario')){	function valida_usuario($id_usu,$id_sec) {			global $connection;			$q_validausuario = "SELECT id_usuario, id_secciones from usuarios_permisos where id_usuario='$id_usu' and id_secciones='$id_sec' order by id_usuario";			$arr_validausuario = mysqli_query($connection, $q_validausuario) or die('Error en llamada 37');			$numrv = mysqli_num_rows($arr_validausuario);			if ($numrv > 0){				return true;			}else{				return false;			}			};};

//Funciones para asignacion y busqueda de permisos para usuarios.
if(!function_exists('busca_permiso_modifica')){	function busca_permiso_modifica($id_usu,$id_sec) {			global $connection;			$q_permisomodifica = "SELECT id_usuario, id_secciones from usuarios_permisos where  id_usuario='$id_usu' and id_secciones='$id_sec' and modificar='1' order by id_usuario";			$arr_modifica = mysqli_query($connection, $q_permisomodifica) or die('Error en llamada 37');			$numr = mysqli_num_rows($arr_modifica);			if ($numr > 0){				return true;			}			return false;	};};if(!function_exists('busca_permiso_ingresar')){function busca_permiso_ingresar($id_usu,$id_sec) {		global $connection;		$q_permisoingresa = "SELECT id_usuario, id_secciones from usuarios_permisos where  id_usuario='$id_usu' and id_secciones='$id_sec' and ingresar='1' order by id_usuario";		$arr_ingresa = mysqli_query($connection, $q_permisoingresa) or die('Error en llamada 37');		$numri = mysqli_num_rows($arr_ingresa);	   	if ($numri > 0){			return true;		}        return false;};};if(!function_exists('busca_permiso_eliminar')){function busca_permiso_eliminar($id_usu,$id_sec) {		global $connection;		$q_permisoelimina = "SELECT id_usuario, id_secciones from usuarios_permisos where  id_usuario='$id_usu' and id_secciones='$id_sec' and eliminar='1' order by id_usuario";		$arr_eimina = mysqli_query($connection, $q_permisoelimina) or die('Error en llamada 37');		$numre = mysqli_num_rows($arr_eimina);	   	if ($numre > 0){			return true;		}        return false;};};if(!function_exists('comillas')){function comillas($txt){  $txt_t="";  $l=strlen($txt);  for($i=0;$i<$l;$i++)  {    if(substr($txt,$i,1)=='"')      $txt_t=$txt_t."&quot;";    else      $txt_t=$txt_t.substr($txt,$i,1);  }  return($txt_t);}}if(!function_exists('cargames')){function cargames($mes_f){if ($mes_f=='01'){$mes_letra="Enero";}if ($mes_f=='02'){$mes_letra="Febrero";}if ($mes_f=='03'){$mes_letra="Marzo";}if ($mes_f=='04'){$mes_letra="Abril";}if ($mes_f=='05'){$mes_letra="Mayo";}if ($mes_f=='06'){$mes_letra="Junio";}if ($mes_f=='07'){$mes_letra="Julio";}if ($mes_f=='08'){$mes_letra="Agosto";}if ($mes_f=='09'){$mes_letra="Septiembre";}if ($mes_f=='10'){$mes_letra="Octubre";}if ($mes_f=='11'){$mes_letra="Noviembre";}if ($mes_f=='12'){$mes_letra="Diciembre";}return $mes_letra;}}
?>